// Third-path independent verification: 20 fixtures (TP-01..TP-20) whose expected values were
// computed by tests/thirdpath/independent_verify.py — Python 3 + decimal.Decimal, transcribed
// directly from docs/CALCULATION_SPEC.md WITHOUT reading production calc.ts/estimateMath.ts or
// the existing TypeScript/Decimal.js oracle (tests/oracle/oracle.ts). Different language,
// different runtime, different arithmetic library, independently authored formulas.
//
// Expected values here are copy-pasted from tests/thirdpath/fixtures.json (generated by the
// Python script) — NOT recomputed at test time — so this file is a frozen assertion against
// that independent computation. See tests/thirdpath/WORKED_EXAMPLES.md for the human-readable
// formulas and intermediate steps behind every fixture.
import { describe, it, expect } from "vitest";
import { calculateEstimate, calculateRequiredSellingPrice, calculateMargin } from "../../src/lib/calc";
import { evaluateEntity } from "../../src/lib/estimateMath";
import type { ProjectSection, Rounding } from "../../src/lib/types";

const REL_TOL = 1e-9;
const ABS_TOL = 1e-6;

function close(actual: number, expected: number): boolean {
  if (Object.is(actual, expected)) return true;
  if (!Number.isFinite(actual) || !Number.isFinite(expected)) return false;
  const diff = Math.abs(actual - expected);
  return diff <= ABS_TOL || diff <= REL_TOL * Math.max(Math.abs(actual), Math.abs(expected));
}

function num(s: string | null): number | null {
  if (s === null) return null;
  return Number(s);
}

describe("TP-01..TP-10: single-section fixtures (calculateEstimate)", () => {
  const cases: Array<{ id: string; input: any; expected: any }> = [
    { id: "TP-01", input: { length_ft: 40, width_ft: 20, thickness_in: 4, allowance_pct: 10, rounding: "quarter", ready_mix_rate: 165, labor: 1200, forms: 180, reinforcement: 220, equipment: 150, other: 50, overhead_pct: 15, target_margin_pct: 30, selling_price: 4200 }, expected: { areaSqFt: "800", netCubicYards: "9.8765432098765432098765432098765432098765432098763", orderQuantityYd3: "11.00", directCost: "3615.00", trueCost: "4157.2500", requiredSellingPrice: "5938.9285714285714285714285714285714285714285714286", currentMargin: "0.010178571428571428571428571428571428571428571428571" } },
    { id: "TP-02", input: { length_ft: 25, width_ft: 25, thickness_in: 5, allowance_pct: 8, rounding: "half", ready_mix_rate: 170, labor: 1400, forms: 200, reinforcement: 250, equipment: 100, other: 0, overhead_pct: 12, target_margin_pct: 28, selling_price: 5000 }, expected: { areaSqFt: "625", netCubicYards: "9.6450617283950617283950617283950617283950617283952", orderQuantityYd3: "10.5", directCost: "3735.0", trueCost: "4183.200", requiredSellingPrice: "5810.0", currentMargin: "0.16336" } },
    { id: "TP-03", input: { length_ft: 12, width_ft: 12, thickness_in: 4, allowance_pct: 0, rounding: "none", ready_mix_rate: 160, labor: 300, forms: 50, reinforcement: 0, equipment: 0, other: 0, overhead_pct: 10, target_margin_pct: 20, selling_price: 900 }, expected: { areaSqFt: "144", netCubicYards: "1.7777777777777777777777777777777777777777777777778", orderQuantityYd3: "1.7777777777777777777777777777777777777777777777778", directCost: "634.44444444444444444444444444444444444444444444445", trueCost: "697.88888888888888888888888888888888888888888888890", requiredSellingPrice: "872.36111111111111111111111111111111111111111111112", currentMargin: "0.22456790123456790123456790123456790123456790123456" } },
    { id: "TP-04", input: { length_ft: 80, width_ft: 10, thickness_in: 6, allowance_pct: 12, rounding: "whole", ready_mix_rate: 175, labor: 2200, forms: 300, reinforcement: 400, equipment: 250, other: 100, overhead_pct: 18, target_margin_pct: 32, selling_price: 8500 }, expected: { areaSqFt: "800", netCubicYards: "14.814814814814814814814814814814814814814814814815", orderQuantityYd3: "17", directCost: "6225", trueCost: "7345.50", requiredSellingPrice: "10802.205882352941176470588235294117647058823529412", currentMargin: "0.13582352941176470588235294117647058823529411764706" } },
    { id: "TP-05", input: { length_ft: 0, width_ft: 30, thickness_in: 4, allowance_pct: 10, rounding: "quarter", ready_mix_rate: 165, labor: 500, forms: 0, reinforcement: 0, equipment: 0, other: 0, overhead_pct: 10, target_margin_pct: 25, selling_price: 600 }, expected: { areaSqFt: "0", netCubicYards: "0", orderQuantityYd3: "0.00", directCost: "500.00", trueCost: "550.000", requiredSellingPrice: "733.33333333333333333333333333333333333333333333333", currentMargin: "0.083333333333333333333333333333333333333333333333333" } },
    { id: "TP-06", input: { length_ft: 15, width_ft: 15, thickness_in: 0, allowance_pct: 5, rounding: "none", ready_mix_rate: 160, labor: 200, forms: 0, reinforcement: 0, equipment: 0, other: 0, overhead_pct: 10, target_margin_pct: 20, selling_price: 300 }, expected: { areaSqFt: "225", netCubicYards: "0", orderQuantityYd3: "0.00", directCost: "200.00", trueCost: "220.000", requiredSellingPrice: "275.00", currentMargin: "0.26666666666666666666666666666666666666666666666667" } },
    { id: "TP-07", input: { length_ft: -10, width_ft: 20, thickness_in: 4, allowance_pct: 10, rounding: "none", ready_mix_rate: 165, labor: 0, forms: 0, reinforcement: 0, equipment: 0, other: 0, overhead_pct: 10, target_margin_pct: 25, selling_price: 50 }, expected: { areaSqFt: "0", netCubicYards: "0", orderQuantityYd3: "0", directCost: "0", trueCost: "0", requiredSellingPrice: "0", currentMargin: "1" } },
    { id: "TP-08", input: { length_ft: 33, width_ft: 3, thickness_in: 6, allowance_pct: 0, rounding: "whole", ready_mix_rate: 150, labor: 0, forms: 0, reinforcement: 0, equipment: 0, other: 0, overhead_pct: 0, target_margin_pct: 0, selling_price: 0 }, expected: { areaSqFt: "99", netCubicYards: "1.8333333333333333333333333333333333333333333333333", orderQuantityYd3: "2", directCost: "300", trueCost: "300", requiredSellingPrice: "300", currentMargin: null } },
    { id: "TP-09", input: { length_ft: 18, width_ft: 9, thickness_in: 4, allowance_pct: 15, rounding: "quarter", ready_mix_rate: 168, labor: 650, forms: 90, reinforcement: 110, equipment: 60, other: 30, overhead_pct: 14, target_margin_pct: 100, selling_price: 3000 }, expected: { areaSqFt: "162", netCubicYards: "2.0000000000000000000000000000000000000000000000000", orderQuantityYd3: "2.50", directCost: "1360.00", trueCost: "1550.4000", requiredSellingPrice: null, currentMargin: "0.4832" } },
    { id: "TP-10", input: { length_ft: 45, width_ft: 22, thickness_in: 5, allowance_pct: 9, rounding: "half", ready_mix_rate: 172, labor: 1650, forms: 210, reinforcement: 260, equipment: 140, other: 45, overhead_pct: 16, target_margin_pct: 27, selling_price: 6800 }, expected: { areaSqFt: "990", netCubicYards: "15.277777777777777777777777777777777777777777777778", orderQuantityYd3: "17.0", directCost: "5229.0", trueCost: "6065.640", requiredSellingPrice: "8309.0958904109589041095890410958904109589041095890", currentMargin: "0.10799411764705882352941176470588235294117647058824" } },
  ];

  for (const c of cases) {
    it(`${c.id}: production matches independent Python/decimal computation`, () => {
      const result = calculateEstimate({
        dimensions: { lengthFt: c.input.length_ft, widthFt: c.input.width_ft, thicknessIn: c.input.thickness_in, allowancePercent: c.input.allowance_pct, rounding: c.input.rounding as Rounding },
        costs: { readyMixRatePerYd3: c.input.ready_mix_rate, laborCost: c.input.labor, formsCost: c.input.forms, reinforcementCost: c.input.reinforcement, equipmentCost: c.input.equipment, otherCost: c.input.other },
        pricing: { overheadPercent: c.input.overhead_pct, targetMarginPercent: c.input.target_margin_pct, sellingPrice: c.input.selling_price },
      });

      expect(close(result.quantity.areaSqFt, num(c.expected.areaSqFt)!)).toBe(true);
      expect(close(result.quantity.netCubicYards, num(c.expected.netCubicYards)!)).toBe(true);
      expect(close(result.quantity.orderQuantityYd3, num(c.expected.orderQuantityYd3)!)).toBe(true);
      expect(close(result.cost.directCost, num(c.expected.directCost)!)).toBe(true);
      expect(close(result.cost.trueCost, num(c.expected.trueCost)!)).toBe(true);

      const expectedRequired = num(c.expected.requiredSellingPrice);
      if (expectedRequired === null) {
        expect(result.pricing.requiredSellingPrice).toBe(Infinity);
      } else {
        expect(close(result.pricing.requiredSellingPrice, expectedRequired)).toBe(true);
      }

      const expectedMargin = num(c.expected.currentMargin);
      expect(result.pricing.currentMargin === null).toBe(expectedMargin === null);
      if (expectedMargin !== null && result.pricing.currentMargin !== null) {
        expect(close(result.pricing.currentMargin, expectedMargin)).toBe(true);
      }
    });
  }
});

describe("TP-11..TP-15: multi-section fixtures (evaluateEntity)", () => {
  function sec(l: number, w: number, t: number): ProjectSection {
    return { id: "s", name: "s", lengthFt: l, widthFt: w, thicknessIn: t };
  }

  const cases = [
    { id: "TP-11", sections: [[50, 12, 4], [10, 10, 4]], allowance_pct: 10, rounding: "quarter", ready_mix_rate: 165, labor: 1400, forms: 200, reinforcement: 250, equipment: 120, other: 40, overhead_pct: 15, target_margin_pct: 30, selling_price: 4800, expected: { netCubicYards: "8.6419753086419753086419753086419753086419753086420", orderQuantityYd3: "9.75", trueCost: "4161.5625", requiredSellingPrice: "5945.0892857142857142857142857142857142857142857143", currentMargin: "0.1330078125" } },
    { id: "TP-12", sections: [[20, 20, 4], [20, 20, 4], [20, 20, 4]], allowance_pct: 5, rounding: "none", ready_mix_rate: 160, labor: 2000, forms: 0, reinforcement: 0, equipment: 0, other: 0, overhead_pct: 10, target_margin_pct: 25, selling_price: 6000, expected: { netCubicYards: "14.814814814814814814814814814814814814814814814814", orderQuantityYd3: "15.555555555555555555555555555555555555555555555555", trueCost: "4937.7777777777777777777777777777777777777777777777", requiredSellingPrice: "6583.7037037037037037037037037037037037037037037036", currentMargin: "0.17703703703703703703703703703703703703703703703705" } },
    { id: "TP-13", sections: [[30, 0, 4], [20, 15, 4]], allowance_pct: 10, rounding: "none", ready_mix_rate: 165, labor: 800, forms: 0, reinforcement: 0, equipment: 0, other: 0, overhead_pct: 12, target_margin_pct: 25, selling_price: 2200, expected: { netCubicYards: "3.7037037037037037037037037037037037037037037037037", orderQuantityYd3: "4.0740740740740740740740740740740740740740740740741", trueCost: "1648.8888888888888888888888888888888888888888888889", requiredSellingPrice: "2198.5185185185185185185185185185185185185185185185", currentMargin: "0.25050505050505050505050505050505050505050505050505" } },
    { id: "TP-14", sections: [[60, 18, 4]], allowance_pct: 10, rounding: "quarter", ready_mix_rate: 165, labor: 1800, forms: 250, reinforcement: 300, equipment: 200, other: 100, overhead_pct: 15, target_margin_pct: 30, selling_price: 5500, expected: { netCubicYards: "13.333333333333333333333333333333333333333333333333", orderQuantityYd3: "14.75", trueCost: "5846.3125", requiredSellingPrice: "8351.875", currentMargin: "-0.062965909090909090909090909090909090909090909090909" } },
    { id: "TP-15", sections: [[15, 15, 4], [15, 15, 4]], allowance_pct: 20, rounding: "whole", ready_mix_rate: 170, labor: 900, forms: 100, reinforcement: 100, equipment: 50, other: 0, overhead_pct: 13, target_margin_pct: 28, selling_price: 3300, expected: { netCubicYards: "5.5555555555555555555555555555554", orderQuantityYd3: "7", trueCost: "2644.20", requiredSellingPrice: "3672.5", currentMargin: "0.19872727272727272727272727272727272727272727272727" } },
  ];

  for (const c of cases) {
    it(`${c.id}: production matches independent Python/decimal computation`, () => {
      const result = evaluateEntity({
        sections: c.sections.map(([l, w, t]) => sec(l, w, t)),
        allowancePercent: c.allowance_pct,
        rounding: c.rounding as Rounding,
        costs: { readyMixRatePerYd3: c.ready_mix_rate, laborCost: c.labor, formsCost: c.forms, reinforcementCost: c.reinforcement, equipmentCost: c.equipment, otherCost: c.other },
        overheadPercent: c.overhead_pct,
        targetMarginPercent: c.target_margin_pct,
        sellingPrice: c.selling_price,
      });

      expect(close(result.netCubicYards, Number(c.expected.netCubicYards))).toBe(true);
      expect(close(result.orderQuantityYd3, Number(c.expected.orderQuantityYd3))).toBe(true);
      expect(close(result.trueCost, Number(c.expected.trueCost))).toBe(true);
      expect(close(result.requiredSellingPrice, Number(c.expected.requiredSellingPrice))).toBe(true);
      expect(close(result.currentMargin!, Number(c.expected.currentMargin))).toBe(true);
    });
  }
});

describe("TP-16..TP-20: pricing-only fixtures (calculateRequiredSellingPrice / calculateMargin)", () => {
  const cases = [
    { id: "TP-16", true_cost: 5000, target_margin_pct: 25, selling_price: 6667, expected: { requiredSellingPrice: "6666.6666666666666666666666666666666666666666666667", currentMargin: "0.25003749812509374531273436328183590820458977051147" } },
    { id: "TP-17", true_cost: 8441, target_margin_pct: 30, selling_price: 9800, expected: { requiredSellingPrice: "12058.571428571428571428571428571428571428571428571", currentMargin: "0.13867346938775510204081632653061224489795918367347" } },
    { id: "TP-18", true_cost: 1000, target_margin_pct: 50, selling_price: 0, expected: { requiredSellingPrice: "2000", currentMargin: null } },
    { id: "TP-19", true_cost: 0, target_margin_pct: 30, selling_price: 500, expected: { requiredSellingPrice: "0", currentMargin: "1" } },
    { id: "TP-20", true_cost: 2500, target_margin_pct: 99, selling_price: 250000, expected: { requiredSellingPrice: "250000", currentMargin: "0.99" } },
  ];

  for (const c of cases) {
    it(`${c.id}: production matches independent Python/decimal computation`, () => {
      const rp = calculateRequiredSellingPrice(c.true_cost, c.target_margin_pct);
      const m = calculateMargin(c.selling_price, c.true_cost);
      expect(close(rp, Number(c.expected.requiredSellingPrice))).toBe(true);
      const expectedMargin = c.expected.currentMargin === null ? null : Number(c.expected.currentMargin);
      expect(m === null).toBe(expectedMargin === null);
      if (m !== null && expectedMargin !== null) expect(close(m, expectedMargin)).toBe(true);
    });
  }
});
